services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    ports:
      - 443:443
      - 8080:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./src:/var/www/html
    environment:
      - SHOP_DOMAIN=shop.pg.wojtecs.com
    depends_on:
      - prestashop
    networks:
      - frontend
      - backend

  prestashop:
    build:
      context: .
      dockerfile: Dockerfile.prestashop
      target: dev
    container_name: prestashop
    depends_on:
      - db
      - valkey
    volumes:
      - ./src:/var/www/html
    networks:
      - backend
  db:
    image: mariadb:12.0
    restart: unless-stopped
    container_name: db
    expose:
      - 3306
    # ports: # for dev purposes only
    #   - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: prestashop
    networks:
      - backend
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    command: [ "valkey-server", "--appendonly", "yes" ]
    expose:
      - 6379
    volumes:
      - valkey_data:/data
    networks:
      - backend

volumes:
  # prestashop_data:
  mariadb-data:
  caddy_data:
  caddy_config:
  valkey_data:


networks:
  frontend:
  backend:
