services:
  db:
    image: mariadb:12.0
    restart: unless-stopped
    container_name: db
    expose:
      - 3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: prestashop
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db-network

volumes:
  mariadb-data:

networks:
  db-network:
    name: prestashop-db-network
