FROM prestashop/prestashop:1.7.8.11-fpm AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev

RUN pecl install redis && \
    docker-php-ext-enable redis

# Experimental
RUN echo 'session.save_handler = redis' > /usr/local/etc/php/conf.d/zz-redis-sessions.ini && \
    echo 'session.save_path = "tcp://valkey:6379?database=2&prefix=ps_sess:"' >> /usr/local/etc/php/conf.d/zz-redis-sessions.ini
# ============

RUN apt-get purge -y --auto-remove \
    build-essential \
    libssl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

FROM base AS prod
RUN rm -rf /var/www/html/* /tmp/data-ps
COPY --chown=www-data:www-data src /var/www/html
COPY Prestashop.prod.entrypoint.sh /tmp/docker_run.sh
COPY backup/db.sh /usr/local/bin/db.sh
COPY backup/backup_20260115_112618.sql.gz.enc /tmp/db_backup.sql.gz.enc
RUN chmod +x /tmp/docker_run.sh && \
    chmod +x /usr/local/bin/db.sh


FROM base AS dev
COPY Prestashop.gitignore /tmp/Prestashop.gitignore
COPY Prestashop.dev.entrypoint.sh /tmp/docker_run.sh
RUN chmod +x /tmp/docker_run.sh