services:
  caddy:
    image: ghcr.io/vv01t3k/some-pg-action-prestashop/caddy:latest
    hostname: caddy
    ports:
      - target: 443
        published: 19781
        mode: host
    volumes:
      - BE_197815_prestashop_src:/var/www/html:ro
    environment:
      SHOP_DOMAIN: shop.pg.wojtecs.com
      SHOP_PORT: 19781
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == student-swarm01
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  prestashop:
    image: ghcr.io/vv01t3k/some-pg-action-prestashop/prestashop:latest
    hostname: prestashop
    volumes:
      - BE_197815_prestashop_src:/var/www/html
    environment:
      DB_HOST: student-swarm01.maas
      DB_PORT: 3306
      DB_NAME: BE_197815_prestashop
      DB_USER: root
      DB_PASSWORD: student
      DB_BACKUP_KEY: OHVpHhQ5z0ke5HCulYXecBXBeA1Q4G1Wm7h6CSXIofI=
      SHOP_DOMAIN: shop.pg.wojtecs.com
      SHOP_PORT: 19781
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname != student-swarm04
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  valkey:
    image: valkey/valkey:9-alpine
    hostname: valkey
    command: [ "valkey-server", "--appendonly", "yes" ]
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  mailpit:
    image: axllent/mailpit:latest
    hostname: mailhog
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
volumes:
  BE_197815_prestashop_src:
networks:
  backend:
    name: BE_197815_backend
    driver: overlay