services:
  db:
    image: mariadb:12.0
    restart: unless-stopped
    container_name: ${DB_HOST:-db}
    expose:
      - ${DB_PORT:-3306}
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-dev}
      MYSQL_DATABASE: ${DB_NAME:-prestashop}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_USER: ${DB_USER:-root}
      PMA_PASSWORD: ${DB_PASSWORD:-dev}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-network

volumes:
  mariadb-data:

networks:
  db-network:
    name: prestashop-db-network
