x-node-environment: &node-env
  SE_EVENT_BUS_HOST: selenium-hub
  SE_EVENT_BUS_PUBLISH_PORT: 4442
  SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  SE_NODE_MAX_SESSIONS: 3
  SE_START_VNC: ${SE_START_VNC:-false}
  SE_VNC_NO_PASSWORD: 1

services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    environment:
      GRID_MAX_SESSION: 5
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.15.0
    container_name: selenium-chrome
    depends_on:
      - selenium-hub
    environment:
      <<: *node-env
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2gb
    ports:
      - "7900:7900"

  firefox:
    image: selenium/node-firefox:4.15.0
    container_name: selenium-firefox
    depends_on:
      - selenium-hub
    environment:
      <<: *node-env
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2gb
    ports:
      - "7901:7900"
